emoji_id1 = '1242378242715816006'
emoji_id2 = '1247996894966321272'
emoji_id3 = '1253013115189329991'
emoji_id4 = '1242290434600865802'
emoji_id5 = '1242378240639897631'
emoji_id6 = '1251918163310936136'
emoji_id7 = '1253035827949469736'

# Sintaxe dos emojis personalizados
emoji1 = f'<:catb_hardworker:{emoji_id1}>'
emoji2 = f'<:simbol_modorange:{emoji_id2}>'
emoji3 = f'<:pz_Zombie:{emoji_id3}>'
emoji4 = f'<:pz_spiffo:{emoji_id4}>'
emoji5 = f'<:catb_pray:{emoji_id5}>'
emoji6 = f'<:heart_green:{emoji_id6}>'
emoji7 = f'<:heart_orange:{emoji_id7}>'

# ID do canal
ip_porta = "<#1245401180159479859>" # substitua pelo ID real do canal
lojas = "<#1251263827815825428>"
ticket = "<#1241170505579626617>"
midias = "<#1241169070116700170>"
duvidas = "<#1252336740404957327>"

# Menção de usuarios
princesa = "<@377121416333754379>"
freitinhas = "<@733722652614852649>"

server = (
        f"# 𝐈𝐧𝐟𝐨-𝐒𝐞𝐫𝐯𝐞𝐫 {emoji4} #\n\n"
        f"**O servidor é público, para acessar use essas informações {emoji1}**\n"
        f"**IP: 181.215.236.42 📡**\n"
        "**PORTA: 16066 🔑**\n\n"
        f"**{emoji2} O PVP está ligado o tempo todo, por isso cuidado para não machucar o amiguinho sem querer, danos por atropelamento também.**\n\n"
        f"{emoji2} Olhe todos os nossos mods [aqui](https://steamcommunity.com/sharedfiles/filedetails/?id=3250138493)\n\n"
        f"{emoji2} **Todos os dias fazemos restart para manutenção do servidor.\n**"
        "● As 06h10 ; 12h10 ; 18h10 ; 00h10\n"
        "➥ Clique [aqui](https://discord.com/channels/1241052393165160508/1252694520617898014) para acompanhar o status do server\n\n"
        "# **➥ Do mundo 🌍** #\n"
        "● 1 dia = 2h da vida real\n"
        "● Temos um mod para deixar o clima mais realista, ou seja verões mais quentes e invernos frios (cuidado para não morrer de hipotermia).\n"
        "● Fogo desligado\n"
        "● Multi-hit ligado\n"
        "● **Todas as feridas precisam ser limpas, ou seu personagem pode morrer por infecção. Use desinfetante ou bebidas alcóolicas para isso.**\n"
        "● **Para maior imersão o sono está ativado, porém é apenas 2 minutos da vida real para o descanso completo**\n\n"
        "# ➥ XP 🆙 #\n"
        "● Ganho de XP está em 5x\n"
        "● Leitura rápida\n\n"
        "# ➥ Loot 📦 #\n"
        "● Spawn de loot a cada 14 dias do jogo\n"
        "● Loot: extremamente raro\n"
        "● Itens largados no chão somem após 12h, use o **colocar item/place item**\n"
        "⤷ Evite deixar coisas importantes no chão, caso o item suma, não nos responsabilizamos.\n"
        f"● Evite ao máximo deixar loot no chão, use uma lixeira para excluir os itens que não quer mais. Isso ajuda a garantir maior fluidez do servidor {emoji5}\n\n"
        f"# ➥ Zumbis {emoji3} #\n"
        "● Spawn 3x\n"
        "● Cadáveres somem após 12h do jogo\n"
        "● Enjoo alto perto dos cadáveres (use máscara perto de muitos corpos)\n"
        "● 1% de corredores no mundo\n"
        "● Força, visão e memória: normal\n"
        "● **Infecção apenas por mordida** ( mortalidade de 2-3 dias)\n\n"
        "# ➥ Safehouse 🔑 #\n"
        "● É permitido apenas uma safehouse por jogador, mas pode participar de outras\n"
        "● A reinvindicação só pode ser feita em lugares residenciais ( prédios laranjas no mapa)\n\n"
        "# ➥ Carros 🚘 # \n"
        "● É possível dar claim em até 8 carros ( caretinhas também contam)\n"
        "⤷ Clique com o botão direito no chão para acessar o menu de reinvindicação de carros\n\n"
        "# ➥ Economia 💵 # \n"
        "● Tem 2 formas de ganhar dinheiro:\n"
        "⤷ Matando zumbis (ao matar zumbis, você encontrará dinheiro em seus cadáveres)\n"
        "⤷ Ou vendendo itens nas lojinhas\n"
        "● Clique [aqui](https://drive.google.com/file/d/1wVg2VHCWlyShZ-vr4WZmMMMfOGPKXYdE/view) para ver como juntar o dinheiro todo de uma vez.\n"
        "⤷ Para colocar o dinheiro na carteira, clique no dinheiro e selecione a opção **place in wallet**\n"
        "⤷ Para poder usar o dinheiro nas lojas, seu dinheiro deve estar na **Wallet**\n"
        "● Todo player nasce com $25 na carteira, para acessar a carteira aperte `J`\n"
        "● **Cuidado ao morrer, pois você perde 50% do valor que estava na sua carteira, sempre tenha uma quantia em outro lugar. Aviso dado**\n"
        f"● A localização das lojas está em {lojas}\n"
        "● **Proibido mexer na estrutura das lojas, passível de advertência.**\n\n"
    )

rules_1 = (
        "# **Boas vindas ao Terminus!** #\n"
        f"**Somos um servidor novo e em crescimento**\n"
        f"**de project zomboid  {emoji4}**\n\n"
        "## **➥ Da administração** ##\n"
        "● 1.1. Seja respeitoso com a equipe de administração. Qualquer forma de desrespeito ou agressão pode resultar em advertências ou, em casos graves, banimento. Nosso objetivo é manter um ambiente harmonioso e acolhedor para todos os membros da comunidade.\n"
        f"● 1.2. O servidor é hosteado por uma empresa terceira, e nós administramos. ➥ {princesa} e {freitinhas}.\n"
        f"● 1.3. **Evite incomodar os administradores em mensagens privadas e também evite mencioná-los nas mensagens. Se precisar entrar em contato com um administrador, use o canal {ticket}, pois é a maneira mais rápida de conseguir assistência.**\n"
        "● 1.4. Somos uma equipe pequena lidando com muitas responsabilidades para garantir uma experiência agradável a todos no jogo. **Pedimos que tenha paciência, pois também temos obrigações fora do jogo.**\n"
        "● 1.5. Evite repetir comentários sobre lag ou outras instabilidades que possam ocorrer no servidor. A equipe de administração está ciente desses problemas e, sempre que possível, iremos investigá-los.\n"
        "● 1.6. Não realizamos reembolsos de doações. As doações são uma forma de ajudar o servidor e, como agradecimento, os doadores recebem brindes. Além disso, não reembolsamos itens de recompensa de doação perdidos em qualquer situação.\n"
        "● 1.7. Todas as denúncias serão investigadas cuidadosamente. Para fazer uma denúncia, por favor, abra um ticket e converse diretamente com um administrador. Certifique-se de apresentar provas, como capturas de tela, vídeos, áudios ou testemunhas, para auxiliar na investigação.\n"
        "● É importante estar ciente de que nossa variedade de mods pode ocasionalmente causar alguns bugs, considerando que o jogo ainda está em desenvolvimento, mas estamos comprometidos em oferecer uma experiência divertida e emocionante para todos os nossos jogadores!\n\n"
        "## **➥ Regras de Convivência no Discord** ##\n"
        "● 2.1. Indivíduos que apresentarem comportamento rude, explosivo ou agressivo não serão tolerados. Monitoraremos as conversas no Discord e no jogo. O banimento ocorrerá sem aviso prévio. Este é um aviso oficial.\n"
        "● 2.2. Não serão tolerados discursos de ódio ou qualquer forma de discriminação racial, social ou de gênero. Aqueles que violarem essa política serão punidos.\n"
        "● 2.3. Pedimos gentileza e respeito mútuo. Valorizamos o respeito e a cordialidade como prioridade. Evite ofender, provocar ou assediar outros membros ou administradores.\n"
        "● 2.4. Não é permitido enviar spam ou conteúdo inadequado. Mensagens repetitivas no chat ou qualquer coisa ofensiva, vulgar ou imprópria serão motivo de advertência ou banimento.\n"
        f"● 2.5. Utilize cada categoria de canais do Discord de acordo com sua finalidade. Poste fotos, vídeos e links no {midias}, e etc. A organização adequada ajuda a manter o ambiente mais claro e útil para todos.\n"
        f"● 2.6. **Se tiver alguma dúvida pequena, mande no canal {duvidas}, assim a comunidade também pode responder. Para dúvidas maiores abra um ticket para falar com um adm.**\n"
        "● 2.7. Não nos envolvemos em disputas pessoais entre jogadores, a menos que haja violação das regras.\n"
        "● 2.8. Não incentive conflitos ou discórdias entre os jogadores. Isso pode resultar em advertência ou banimento. Nosso objetivo é manter um ambiente harmonioso e amigável para todos.\n\n"
)
rules_2 = (
        "## **➥ In game** ##\n\n"
        "● 3.1. Não toleramos o uso de exploits. Não utilize trapaças ou programas ilegais para obter vantagens no jogo. O banimento será aplicado imediatamente, sem aviso prévio.\n"
        "● 3.2. Não podemos nos responsabilizar por itens perdidos sem evidências, seja por desaparecimento sem comprovação, itens dropados no chão ou perdas durante rollbacks. É importante lembrar que rollbacks ocorrem devido à instabilidade e aos bugs do jogo.\n"
        "● 3.3. Não nos responsabilizamos por mortes de jogadores ou pelo desaparecimento de seus corpos. É importante ressaltar que os corpos podem desaparecer eventualmente, conforme avisado anteriormente.\n"
        "● 3.4. Por favor, não tente ajudar ou fazer favores a terceiros sem o consentimento deles. Alguns jogadores preferem jogar sozinhos. Respeite a escolha e a privacidade de cada um.\n"
        "● 3.5. Não nos intrometeremos na gameplay de nenhum jogador. Não peça para que te salvemos de situações de perigo!\n\n"
        "## **➥ Safehouse** ##\n"
        "● 3.6. Cada jogador pode reivindicar até 1 casa, e fações podem ter 1 prédio (prédio de apartamentos por exemplo) sendo apenas as construções laranjas no mapa.\n"
        "● 3.6.1. Safehouses abandonadas (sem login por mais de 14 dias) serão liberadas automaticamente.\n"
        "● 3.6.2. Incentivamos a construção de muros envolta da safehouse tanto para proteção contra os zumbis, como de outros players.\n"
        "● 3.6.3. A área da safehouse é definida como sendo um raio de 2 tiles ao redor da casa. É possível adquirir uma expansão da safehouse, veja [aqui](https://discord.com/channels/1241052393165160508/1241172074341339209).\n\n"
        "## **➥ Reivindicação de Veículos** ##\n"
        "● 3.7. Cada jogador pode reivindicar até 8 veículos. **Certifique-se de sempre fazer a reivindicação para evitar roubos, veículos sem claim são de inteira responsabilidade do jogador.**\n"
        "● 3.7.1. **É proibido roubar veículos que estejam reivindicados. Caso algum veículo sem reivindicação esteja no terreno da sua casa, ele corre o risco de ser roubado.**\n"
        "● 3.7.2. As carrocerias de caminhonetes estão sempre abertas, por isso, sempre lembre de tirar os itens importantes e guardá-los na sua safehouse.\n"
        "● 3.7.3. Em outros carros, sempre lembre de fechar o porta-malas. **Mesmo que o veículo esteja reivindicado, se o porta-malas estiver aberto, outros jogadores podem pegar os itens.**\n\n"
        "## **➥ Do PVP** ##\n"
        "● 3.8. O PVP está liberado o tempo todo, incluindo dano por armas brancas, armas de fogo e veículos. Tome cuidado para não ferir aliados acidentalmente.\n"
        "● 3.8.1. Pedimos para que não tenha combate dentro das lojas, para evitar a destruição da estrutura. Caso aconteça lutas e teve alguma destruição, favor avisar um adm.\n"
        "● 3.8.2. **Após um combate, o saque de corpos de jogadores mortos é permitido. No entanto, é estritamente proibido destruir, esconder, mover ou de qualquer outra forma manipular itens do jogador morto que impeça que ele possa recuperar o que sobrou no corpo. Assim o player que morreu tem chance de recuperar o que sobrou no corpo.**\n"
        "● 3.8.3. **Após a luta, qualquer forma de 'trash talk', provocação ou comportamento tóxico dentro do discord é passível de advertência, ou dependo do caso, banimento. A LUTA COMEÇA E ACABA DENTRO DO JOGO.**\n"
        "● 3.8.4. O uso de bugs, glitches ou qualquer tipo de exploit do jogo para obter vantagem em combate PVP é estritamente proibido. Qualquer jogador pego utilizando tais métodos será banido permanentemente.\n"
        "● 3.8.5. **É proibido o uso do combatlog (deslogar para não morrer) em combates PVP, se você caiu tire um print e informe a moderação através de um ticket, caso contrário será penalizado.\n"
        "● 3.8.6. É estritamente proibido entrar em uma facção com a intenção de prejudicar seus membros, como matar todos ou roubar itens. Isso inclui qualquer ação que possa ser interpretada como traição ou sabotagem interna.\n"

)
invite = (f"# **𝙐𝙨𝙚 𝙚𝙨𝙨𝙚 𝙡𝙞𝙣𝙠 𝙥𝙖𝙧𝙖 𝙘𝙤𝙣𝙫𝙞𝙙𝙖𝙧 𝙤𝙪𝙩𝙧𝙖𝙨 𝙥𝙚𝙨𝙨𝙤𝙖𝙨 {emoji4}** #\n"
           "https://bit.ly/serverTerminus"
) 
donate = (f"# Apoie o server {emoji6} #\n"
          f"O servidor tem custos mensais e qualquer tipo de apoio é muito bem-vindo. Se você estiver interessado em contribuir de alguma forma ficaremos gratos, e ao fazer uma doação, estará ajudando a manter o servidor ativo.{emoji1}\n\n"
          "## ➥ R$5,00 ##\n"
          "● Cargo de apoiador ✨\n"
          "● Blindagem ou reparo 100% de 1 carro 🚘\n"
          "● 1000 Dólares 💸\n"
          "● 1 cura 🧬\n"
          "● 4 Enlatados 🥫\n"
          "## ➥ R$10,00 ##\n"
          "● Cargo de apoiador ✨\n"
          "● Aumento da zona de safehouse 🔑\n"
          "● Blindagem ou reparo 100% de 1 carro 🚘\n"
          "● 5.000 Dólares 💸\n"
          "● 1 cura 🧬\n"
          "● 10 Enlatados 🥫\n"
          "## ➥ R$15,00 ##\n"
          "● Cargo de apoiador ✨\n"
          "● Aumento da zona de safehouse 🔑\n"
          "● Blindagem ou reparo 100% de 2 carros 🚘\n"
          "● 7.000 Dólares 💸\n"
          "● 2 curas 🧬\n"
          "● 1 arma branca de sua escolha (exceto katana e machete) 🔪\n"
          "● 24 Enlatados 🥫\n"
          "## ➥ R$25,00 ##\n"
          "● Cargo de apoiador ✨\n"
          "● Aumento da zona de safehouse 🔑\n"
          "● Blindagem ou reparo 100% de 2 carros 🚘\n"
          "● 15.000 Dólares 💸\n"
          "● 4 curas 🧬\n"
          "● 1 Carro 100% de sua escolha 🚐\n"
          "● 1 Arma branca de sua escolha 🔪\n"
          "● 1 Arma de fogo da sua escolha (vem com pente cheio e mais 3 caixas de munição) 🔫\n"
          "● 40 Enlatados 🥫\n"
          "## ➥ R$50,00 ##\n"
          "● Cargo de apoiador ✨\n"
          "● Aumento da zona de safehouse 🔑\n"
          "● Blindagem ou reparo 100% de 6 carros 🚘\n"
          "● 50.000 Dólares 💸\n"
          "● 6 curas 🧬\n"
          "● 2 Carros 100% de sua escolha 🚐\n"
          "● 3 Armas brancas de sua escolha 🔪\n"
          "● 1 Arma de fogo da sua escolha (vem com pente cheio e mais 8 caixas de munição) 🔫\n"
          "● 80 Enlatados 🥫\n"
          "## ➥ R$100,00 ##\n"
          "● Cargo de apoiador ✨\n"
          "● Aumento da zona de safehouse 🔑\n"
          "● Blindagem ou reparo 100% de 10 carros 🚘\n"
          "● 80.000 Dólares 💸\n"
          "● 10 curas 🧬\n"
          "● 3 Carros 100% da sua escolha (vem com blindagem pesada) 🚐\n"
          "● 5 Armas brancas da sua escolha 🔪\n"
          "● 3 Armas de fogo da sua escolha (vem com pente cheio e 10 caixas de munição) 🔫\n"
          "● 150 Enlatados 🥫\n"
          "● Mochila OP (tem 300 de espaço mais slot para 3 upgrades) 🎒\n\n"
          f"# Itens que podem ser adquiridos a parte {emoji6} #\n"
          "🔑 Expansão de safehouse ➥ R$6,00\n"
          "🔻 Remover uma trait ➥ R$2,00\n"
          "🚘 Blindagem ou reparo 100% de um carro ➥ R$3,50\n"
          "🔪 1 Arma branca de sua escolha ➥ R$10,00\n"
          "🚗 1 Carro 100% da sua escolha com blindagem ➥ R$15,00\n"
          "🧬 2 Vacinas da cura ou cura 100% do personagem ➥ R$5,00\n"
          f"{emoji7} Restaurar as habilidades da última morte ➥ R$10,00\n\n"
          f"**➥ Todos os doadores, independentemente do valor, receberão o cargo de apoiador como forma de reconhecimento. {emoji6}**"
)  
embed_botton = ("**Qualquer outro valor é bem vindo e pensaremos em algum brinde a altura.**\n\n"
                f"**Saiba que sua presença é muito apreciada, independentemente de qualquer doação. Obrigado pelo apoio! {emoji6}**"
)

